# Generated by Django 5.2.1 on 2025-05-26 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('min_spending_min', models.IntegerField(blank=True, null=True)),
                ('min_spending_max', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(default='台北市', max_length=50)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lane', models.CharField(blank=True, max_length=20, null=True)),
                ('alley', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='請填寫暱稱', max_length=50)),
                ('cafe', models.CharField(default='請填寫咖啡廳名稱', max_length=50)),
                ('address', models.TextField(default='請填寫地址', max_length=50)),
                ('cafe_url', models.URLField(default='請填寫訂位網站連結', null=True)),
                ('del_pass', models.CharField(max_length=50)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafesearch.tag')),
            ],
        ),
    ]
