# Generated by Django 5.2.1 on 2025-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0005_alter_cafe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
