# Generated by Django 5.2.1 on 2025-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0007_tag_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='booking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
