# Generated by Django 5.2.1 on 2025-05-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0008_cafe_booking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
