# Generated by Django 5.2.1 on 2025-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0009_alter_cafe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='address',
        ),
        migrations.AddField(
            model_name='cafe',
            name='alley',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lane',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
