# Generated by Django 5.2.1 on 2025-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0010_remove_cafe_address_cafe_alley_cafe_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='city',
            field=models.CharField(default='台北市', max_length=50),
        ),
    ]
