# Generated by Django 5.2.1 on 2025-05-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='min_spending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
