# Generated by Django 5.2.1 on 2025-05-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0003_rename_min_spending_cafe_min_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='min_price',
            new_name='min_spending',
        ),
    ]
