# Generated by Django 5.2.1 on 2025-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0004_rename_min_price_cafe_min_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
