# Generated by Django 5.2.1 on 2025-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0007_tag_user_remove_cafe_min_spending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
