# Generated by Django 5.2.1 on 2025-05-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0008_rename_min_spending_cafe_min_spending_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
