# Generated by Django 5.2.1 on 2025-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafesearch', '0009_alter_cafe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='alley',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.CharField(default='台北市', max_length=50),
        ),
        migrations.AddField(
            model_name='cafe',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lane',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
