# Generated by Django 5.2.1 on 2025-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafecomment',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
